[project]
name = "github-mail-reader"
version = "0.1.0"
description = ""
authors= [
  { name = "Christophe Simonis", email = "christophe@kn.gl" },
]
requires-python = ">= 3.11"
dependencies = ["rich~=13.3.5", "imap-tools~=1.0.0", "tomli~=2.0.1", "requests~=2.30.0"]
